### ISSUE TITLE
install prob

### ISSUE THREAD

**Issue by dgu123** [opendigitaleducation/springboard#1]
The install process seems outdated and out of synch

**Comment by rdjedjig** [comment]
Bonjour,

Voici une documentation temporaire actualisée. Je vous propose de partir du [springboard OPEN ENT NG](https://github.com/OPEN-ENT-NG/springboard-open-ent) qui est à l'heure actuelle mieux maintenu.

# pré-requis

java 1.7
vertx 2.1.6
postgres 9.4
neo4j 2.3.1
mongodb 3.2.6

# cloner Springboard

```
    git clone git@github.com:OPEN-ENT-NG/springboard-open-ent.git
```

# Installation simple

## Dépôts Maven

Ajouter au fichier {VERTX_HOME}/conf/repos.txt la ligne suivante (Où {VERTX_HOME} est le dossier d'installation de Vert.x) :

```
    maven:http://maven.web-education.net/nexus/content/groups/public/    
```

## Assemblage

Préparer le Springboard . Depuis son dossier de clonage (path-to-our/springboard) lancer :

```
    gradle init // récupère les dépendance
```

Hack => copier manuellement le thème dans le répertoire `assets/themes`

```
    cp -rf deployments/assets/themes/leo/ assets/themes/
```

## Configuration

Dans le fichier conf.properties, vérifier les propriétés suivantes

```
    mode=dev

    host=http://localhost:8090
    httpProxy=true 

    // Neo4J
    neo4jUri=http://localhost:7474
    neo4jEmbedded=false

    // MongoDB
    dbName=${MONGO_DB_NAME}
    mongoHost=localhost
    mongoPort=27017

    // PostgreSQL
    sqlUrl=jdbc:postgresql://localhost:5432/$PSQL_DB_NAME?stringtype=unspecified
    sqlUsername=$PSQL_USER
    sqlPassword=$PSQL_USER_PWD

    // Configuration de l'apparence (skin et thème => 1 skin peut contenir plusieurs thèmes. 1 skin doit être associé à une domaine)
    skin=leo
    skins={"localhost:8090":"leo"}
    themes={"_id": "default","displayName": "default","path": "/assets/themes/leo/default/"},{"_id": "dyslexic","displayName": "dyslexic","path": "/as    sets/themes/leo/dyslexic/"}
```

Générer la configuration Vertx

```
    gradle generateConf // génère la configuration Vertx de tous les modules
```

## Charger le schéma

```
    neo4j-shell < scripts/schema.cypher
```

## Lancer

```
    vertx runMod org.entcore~infra~${entcoreVersion} -conf ent-core.json // valeur de la propriété entcoreVersion dans le fichier conf.properties
```

Le springboard télécharge les modules Vertx  et lance la plate-forme. L'hôte d'accès est **localhost:8090**

_Remarque_ : L'utilisateur qui lance le springboard doit avoir les droits sur le dossier d'installation de Vert.x, pour permettre l'installation de modules (Vert.x) systèmes

**Comment by dgu123** [comment]
Bonjour Rafik,

d' apres ton email,

cloner Springboard

```
git clone git@github.com:OPEN-ENT-NG/springboard-open-ent.git
```

donne :

Cloning into 'springboard-open-ent'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

est ec exacte,

david

2016-10-10 10:01 GMT+02:00 Rafik Djedjig notifications@github.com:

**Comment by dgu123** [comment]
est ce exacte je voulais dire :)

2016-10-10 15:35 GMT+02:00 David Guimard davidguimard21@gmail.com:
